name: CI

on:
  push:
    branches :
      - 'lab**'
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install
        run: dotnet tool install --global coverlet.console --version 6.0.2

      - name: Restore dependencies
        run: dotnet restore spacebattle

      - name: Test Build
        run: dotnet build spacebattle

      - name: Test
        run: coverlet spacebattle\SpaceBattle.Lib.Tests\bin\Debug\net6.0\SpaceBattle.Lib.Tests.dll --target "dotnet" --targetargs "test spacebattle\SpaceBattle.Lib.Tests\SpaceBattle.Lib.Tests.csproj --no-build" --output lcov.info
        
      - name: Format
        run : cd spacebattle && dotnet format --verify-no-changes